### ISSUE TITLE
biological vs numerical timestep

### ISSUE THREAD

**Issue by skefi** [fdschneider/caspr#27]
It would be good to be able to set the number of numerical timestep (=updates) within each biological timestep with the parameters of the model.
(e.g.  if a parameter has a value superior to 1 and the biological timsetep is yearly, we need to screen the lattice several times a year to have a good approximation of the dynamics)
i.e. subs? 
Can iit become easy to update (if not already)?

**Comment by fdschneider** [comment]
Yes. it is already implemented in the update functions of the models. 

But this is quite model dependent. For instance the pred prey model has asynchronous updating and within each annual timestep `width` x `height` random cells are updated, allowing for repeated draws. Each cell has the fair chance to be updated, but no guarantee. Thus, no substeps in that sense are implemented, but they could be. 

The other models have synchronous updating and each timestep is implemented as `subs` substeps (our former delta_t). Within each substep, only a fraction of the annual transition probability is applied. The default value here is set in the model specifications, but it can be provided by the ca() function as an argument that is handed over to the update function call. For instance, you can run the grazing model with 12 instead of the default 10 substeps by calling: 

``` r
ca(l , model = grazing, parms = p, subs = 12)
```

In any case only the full annual timestep is returned to the `ca()` function.

**Comment by fdschneider** [comment]
I am adding this explanation to the package vignette.
